### ISSUE TITLE
There is an issue on last push made on request-wrapper

### ISSUE THREAD

**Issue by punithk** [IBM/node-sdk-core#105]
There seems to be an issue on the request-wrapper file which has been modified just few hours back.

Due to this other package(ibm-watson) which is using this package on version 2.4.3 is having error as follows:

Bad Request: Missing 'version' query parameter
    at RequestWrapper.formatError (/home/masteradmin/lucy-latest/Lucy-Next-Application/node_modules/ibm-cloud-sdk-core/lib/request-wrapper.js:223:21)
    at /home/masteradmin/lucy-latest/Lucy-Next-Application/node_modules/ibm-cloud-sdk-core/lib/request-wrapper.js:211:25
    at Immediate.<anonymous> (/home/masteradmin/lucy-latest/Lucy-Next-Application/node_modules/es6-shim/es6-shim.js:1382:26)
    at processImmediate (internal/timers.js:456:21)
    at process.topLevelDomainCallback (domain.js:137:15) {
  statusText: 'Bad Request',

This is error from Watson assistant as its APIs require version as its query string but its not being sent via this package.

I think issue is that query parameter is not being sent correctly due to these changes because of which all packages using 2.4.3 version of this package and hitting this function is unable to send query parameters as part of the request.

It works fine on previous version of the same package which is before last merge. Issue is on request-wrapper file and clearly requests are not able to send the query parameters.

**Comment by dpopp07** [comment]
@punithk Thank you for the issue - I just became aware of this myself and will have a fix out today.

**Comment by dpopp07** [comment]
Fixed in 2.4.4

**Comment by punithk** [comment]
Thanks for fixing @dpopp07
