### ISSUE TITLE
SDK is not tree shakeable

### ISSUE THREAD

**Issue by Carsten-Leue** [IBM/node-sdk-core#175]
When bundling node applications is it desirable to keep the overall bundle size small, even if the application is only used on the server side. One state of the art mechanism to achieve this is tree shaking, e.g. via webpack.

Tree shaking however only works with ES6 style modules, not with commonjs style modules. Libraries that support tree shaking expose multiple entry points via the `package.json`, one for commonjs (`main`) and one for es6 style modules (`module`). 

Since the SDK is based on TS, transpiled to JS, this is very easy to achieve by adding two compile steps. One for JS (the current one) and one for ES6 based on a derived tsconfig.json, e.g. such as this:

```
{
    "extends": "./tsconfig.json",
    "compilerOptions": {
        "target": "ES6",
        "module": "ESNext",
        "outDir": "./dist/es",
        "declaration": true
    }
}
```

This would help applications tremendously, getting the overall size down and would also avoid as a desirable side effect to exclude test level libraries from production bundles (since they would be tree shaken).

**Comment by padamstx** [comment]
@Carsten-Leue Would you perhaps have an example of a node.js project that is configured in this way?  if so, I'd like to study it a bit to understand more.

**Comment by padamstx** [comment]
@Carsten-Leue Could you perhaps describe how an application should properly bundle the node core, given your changes that have been merged in?   Specifically I'm wondering about a scenario where an application is using an SDK, and that SDK specifies the node core as a dependency.   The application owner wants to bundle the SDK (and by extension the node core) with his app.
This is related to https://github.com/IBM/node-sdk-core/issues/185
