### ISSUE TITLE
Update axios version to 0.25.0

### ISSUE THREAD

**Issue by bhupnaik** [IBM/node-sdk-core#190]
- We have identified a security vulnerability in the route that ends with `ibm-cloud-sdk-core>axios>follow-redirects` for `follow-redirects` version `1.14.6`.
- Same has been resolved in `follow-redirects` version `1.14.7` which is consumed by `axios` version `0.25.0`
- `ibm-cloud-sdk-core`  is currently using `axios` version `0.21.4` (https://github.com/IBM/node-sdk-core/blob/main/package.json#L81)

Upgrading to `axios` version `0.25.0` will help us to resolve this vulnerability.

**Comment by padamstx** [comment]
This will be fixed once [this PR](https://github.com/IBM/node-sdk-core/pull/189) is merged in, which should be soon (today)

**Comment by padamstx** [comment]
The follow-redirects vulnerability issue is fixed in v2.17.9 (just released).
