### ISSUE TITLE
Error: EISDIR: illegal operation on a directory

### ISSUE THREAD

**Issue by azasdimi** [IBM/node-sdk-core#201]
Hello, 
when releasing our Application from Azure DevOps, we encounter this error:

`2022-06-17T12:23:12.2811600Z Copying file: 'node_modules/ibm-cloud-sdk-core/ibm-cloud-sdk-core.d.ts'` 
`2022-06-17T12:23:12.2815569Z Error: EISDIR: illegal operation on a directory, open '/home/site/wwwroot/node_modules/ibm-cloud-sdk-core/docs'`

We noticed that this error started popping up with the latest releases of your package. And specifically because the /docs directory is now appearing as a file.

![Screen Shot 2022-06-21 at 15 45 04](https://user-images.githubusercontent.com/48895094/174814675-b99bc3af-563f-4274-a817-28b32118c6af.png)

We mitigated it, by downgrading to version: 2.17.10 which the error doesn't appear.

Do you have any solutions for that issue apart from downgrading? Is this error planned to be fixed at a later release?

Thank you in advance.

**Comment by dpopp07** [comment]
@azasdimi I believe I know what is happening now. I should have a fix out soon
