### ISSUE TITLE
ibm-cloud-sdk-core is now 4.0.0 which includes major upgrade of axios

### ISSUE THREAD

**Issue by huineng** [IBM/node-sdk-core#223]
Could you please publish a new package ?
maybe not under 0.3.x ? as contains major release of axios

thanks

**Comment by dpopp07** [comment]
@huineng I'm sorry - I don't understand what you are reporting or asking for in this issue

**Comment by huineng** [comment]
sorry , was for a completely different sdk , the cloudant-sdk  that uses this library 
https://github.com/IBM/cloudant-node-sdk/issues/1051
sorry
