### ISSUE TITLE
VpcInstanceAuthenticator uses wrong version, no option to change it

### ISSUE THREAD

**Issue by smirnovigor** [IBM/node-sdk-core#230]
Hi all, I'm using ibm-cloud-sdk-core (v4.0.2), when trying to authenticate with VpcInstanceAuthenticator, getting "Caught exception from VPC 'create_access_token' operation: The `version` value cannot be before `2022-03-01`".

From debug I see that '2021-09-20' passed by default, I don't see any option to change it.

**Comment by padamstx** [comment]
Looking into this now...

**Comment by padamstx** [comment]
@smirnovigor A fix is available in [this PR](https://github.com/IBM/node-sdk-core/pull/231) (branch = fix-vpcauth).  It might take us a day or so to get this tested in a real VPC environment, but if you'd like to try out the fix by using the "fix-vpcauth" branch feel free to do that.
Here is a link to the npm docs on how to define a dependency on a specific branch:
https://docs.npmjs.com/cli/v8/configuring-npm/package-json#git-urls-as-dependencies

**Comment by smirnovigor** [comment]
Thank you, it works fine, waiting for release

**Comment by padamstx** [comment]
Thanks for giving that a try.  We'll get this fix delivered soon.
