### ISSUE TITLE
Missing @types/debug into package.json (devDependencies)

### ISSUE THREAD

**Issue by LsKoder** [IBM/node-sdk-core#259]
### Error Description:
Library `debug` is specified into dependencies, but related @types/debug is missing.
Transpiler produces the following error at build time:
```
node_modules/ibm-cloud-sdk-core/es/lib/get-new-logger.d.ts:16:26 - error TS7016: Could not find a declaration file for module 'debug'. '/node_modules/debug/src/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/debug` if it exists or add a new declaration (.d.ts) file containing `declare module 'debug';`
16 import { Debugger } from 'debug';
```

### Solution:
Add `"@types/debug": "^4.1.12"` into devDependencies
https://github.com/IBM/node-sdk-core/blob/f6cc1c5e268a5ab4d0137d77e9a30e03350adf7b/package.json#L79

### Workaround (Tested):
Add explicit `"@types/debug": "^4.1.12"` into the main project, in addition to "node-sdk-core".

Thanks

**Comment by padamstx** [comment]
@LsKoder what, specifically, were you building when you encountered this error?  Just want to make sure I have the complete view of the problem and solution.  Thanks!
