### ISSUE TITLE
Bug: Missing offset in response in 0.10.1

### ISSUE THREAD

**Issue by JurajNyiri** [IBM/node-sdk-core#285]
**Describe the bug**
Offset is missing from the response.

**To Reproduce**
1. Execute `.postView` with following example arguments:

```
{
  db: 'CHANGE_ME',
  ddoc: 'CHANGE_ME',
  view: 'CHANGE_ME',
  keys: undefined,
  limit: 1,
  includeDocs: false,
  skip: undefined,
  startKeyDocId: undefined,
  startKey: '2024-08-21T08:35:15.899Z', // change me to some startKey based on the view
  endKey: undefined
}
```

2. Observe offset is not returned in the latest version

**Expected behavior**
Offset to be returned.

**Screenshots**

This is response from cloudant REST endpoint:
<img width="224" alt="68747470733a2f2f7a656e6875622e69626d2e636f6d2f696d616765732f3561656231623339363539393532653535613833383731612f37303537653664612d363565372d343635362d613431312d633233303731626334396661" src="https://github.com/user-attachments/assets/08338950-b7d4-4b85-8f81-55beb3462064">

After conversion inside https://github.com/IBM/node-sdk-core/blob/main/lib/base-service.ts#L313, it is dropped.

<img width="215" alt="68747470733a2f2f7a656e6875622e69626d2e636f6d2f696d616765732f3561656231623339363539393532653535613833383731612f33643730313035382d363239642d343731632d613937342d353963386636386632343135" src="https://github.com/user-attachments/assets/275f6ecf-157c-4dc6-8097-244e9808146e">

This is caused by `deserializerFn` https://github.com/IBM/cloudant-node-sdk/blob/main/cloudant/v1.ts#L11066 not having "offset" parameter. After adding it there, like so, it is properly returned.

```
if (obj.offset !== undefined) {
        copy.offset = obj.offset;
}
```

**Additional context**
This is causing issues for our services with offset based logic, calculating when to stop processing the data and showing a proper progress.

It happened sometimes after update from 0.8.x to 0.10.1, most probably inside 0.9.0 introducing other breaking changes, including the map of `total_rows` to `totalRows`.

I was not able to properly compile the ts code and test a fix due to tsc errors I do not have time to investigate how to fix, but an example idea of a fix can be seen inside https://github.com/JurajNyiri/node-sdk-core/commit/3f8de97fa81ae3025568e736eaf66fc585f0a349 .

Alternatively, a condition could be added to also process integers similar to strings (but then other integers being renamed, like totalRows need to be dropped).

**Comment by dpopp07** [comment]
This looks like an issue in the [Cloudant Node SDK](https://github.com/IBM/cloudant-node-sdk), which you linked to above. I suggest opening an issue against that project.
