### ISSUE TITLE
cannot receive response from IBM watson: Body of error is HTTP ClientRequest

### ISSUE THREAD

**Issue by juanpablo64** [IBM/node-sdk-core#73]
Hello! I didn't see an issue related to my problem, so I'll go ahead and tell the problem I am facing. Currently, the app we are using to connect to the watson assistance is behind a DMZ, so, only selected ports are opened, in the case of watson we are using the port 443. The problem is we somehow can't receive the answer after the message has been sent. Here's what the app says when I want to send a message:

![68957529-fdab8d00-07a8-11ea-9b15-cb03815a27d2](https://user-images.githubusercontent.com/7575105/69112536-383e4f80-0a5f-11ea-9bff-f4d00812f3d7.png)
![68973785-edf26f80-07cd-11ea-899c-1f572de656b6](https://user-images.githubusercontent.com/7575105/69112537-383e4f80-0a5f-11ea-852e-2668a91e4278.png)

I wonder if it is related to that port not being opened?

**Comment by germanattanasio** [comment]
You need to allow for 2 requests.
1. First goes to https://iam.cloud.ibm.com/identity/token and retrieves an access_token (this is where you app is failing)
2. Second goes to https://gateway.watsonplatform.net/conversation/api


Both are `https`. In your error, I see `https://https://...` which should not be there.
Can you paste the code you are using to construct the service instance?

**Comment by juanpablo64** [comment]
sure! Here it is :

```
const { WatsonMiddleware }  = require('botkit-middleware-watson');

 const watsonMiddleware = new WatsonMiddleware({

        iam_apikey: process.env.WATSON_APIKEY,
        url: process.env.WATSON_URL,
        workspace_id: process.env.WATSON_WORKSPACE_ID,
        version: '2018-07-10',
        minimum_confidence: 0.5, // (Optional) Default is 0.75
    });

watsonMiddleware.before = async (message, payload) => {

        if (typeof(payload.context) === 'undefined') {
            var context = {
                context: {
                    user_id: userId.user_id,
                    name:userId.name,
                    prev_interview: '',
                    prev_interview_detail: '',
                    age: '',
                    place: '',
                    civil_state: '',
                    prev_studies: '',
                    time_availability: '',
                }
            };

            Object.assign(payload, context);
        }

        return payload;
    };
```

contents of the .env file

WATSON_APIKEY=*apikey goes gere*
WATSON_URL=https://gateway-lon.watsonplatform.net/assistant/api
WATSON_WORKSPACE_ID=*workspace id goes here*

**Comment by juanpablo64** [comment]
Update: I changed it so now the https part is not repeated, but still get the same error

![image](https://user-images.githubusercontent.com/7575105/69239674-89426680-0b79-11ea-965f-bb7bdc2f0612.png)

![image](https://user-images.githubusercontent.com/7575105/69239688-90697480-0b79-11ea-86a2-79bbdc86553d.png)

**Comment by germanattanasio** [comment]
based on your images, the error is in the token request to IAM, not in the call to Watson. Try following the tutorial here https://cloud.ibm.com/docs/iam?topic=iam-iamtoken_from_apikey and see if you can do a `curl` command and get a token back

**Comment by juanpablo64** [comment]
Hello there! I followed the tutorial and got the exact same results as the expected answers:

```
{"access_token":"long string",
"refresh_token":"long string",
"token_type":"Bearer",
expires_in":3600,
"expiration":1574269358,
"scope":"ibm...
```

but it is still not working.

**Comment by juanpablo64** [comment]
I tried changing the proxy settings of watsonmiddleware, but I get this as currenturl

_currentUrl: 'https://host:port/https://iam.cloud.ibm.com/identity/token'

is this okay? how should I change it?

**Comment by dpopp07** [comment]
@juanpablo64 Have you tried [this method described in the docs](https://github.com/watson-developer-cloud/node-sdk#use-behind-a-corporate-proxy)? It seems like your issue is with the proxy, this may be what you need to fix it

**Comment by juanpablo64** [comment]
it really was, thank you so much! I'll close the issue!
