### ISSUE TITLE
Consider splitting off tests/utils into own package

### ISSUE THREAD

**Issue by MasterOdin** [IBM/node-sdk-core#81]
In v2.0.1, when the tests were converted to typescript, ts-jest was also introduced as a dependency. However, now, when installing this package (or more likely ibm-watson) will show the following error message:
```
$ npm install
npm WARN ts-jest@24.3.0 requires a peer of jest@>=24 <25 but none is installed. You must install peer dependencies yourself.
```

which can be confusing / annoying to end-users to see.

Given that the test utilities exists to provide functionality to downstream modules, and not even to the node-sdk-core itself, it may be good to split it apart into its own publish package which those downstream consumers can still import it as necessary for their testing, but it does not get dragged into production code of external users.

**Comment by dpopp07** [comment]
@MasterOdin Thanks for the issue. I agree, that's pretty annoying. I would prefer to not have to create another package (although that seems like the best solution) so I will try and think about how we might handle this. That said, I don't know how quickly I'll be able to act on this in the midst of other priorities

**Comment by dpopp07** [comment]
@MasterOdin I finally got some time to look at this and thought of a solution to keep the utilities in this package and get rid of the annoying issues around them.

This is in #101, I'd be interested in hearing your thoughts.

**Comment by dpopp07** [comment]
While I know you probably still support doing this long term, I'm going to close this issue for now since the underlying problem has been addressed
