### ISSUE TITLE
Older version libraries coming as dependency

### ISSUE THREAD

**Issue by mumeshr** [IBM/node-sdk-core#99]
- [ ] Steps to reproduce
Add ibm-watson@5.6 library to package.json, it will add  ibm-cloud-sdk-core@2.4.1 as dependency. In return  ibm-cloud-sdk-core@2.4.1 is adding ts-jest@24.3.0 instead of latest. And this version is having a dependency on yargs-parser. Which is failing for contrast.
- [ ] Expected behavior
The application should run with contrast but its failing when contrast is enabled. As yargs-parser referred is older version and creating problems.
- [ ] Actual behavior
Contrast enabled server fail to start and gives a message.
"ERR npm WARN ts-jest@24.3.0 requires a peer of jest@>=24 <25 but none is installed. You must install peer dependencies yourself."
- [ ] Node version
10.16.3
- [ ] SDK version
IBM SDK for Node.js Buildpack v4.3-20200606-1928

### When you open an issue for a feature request, please add as much detail as possible:
- [ ] A descriptive title starting with the service name
ibm-cloud-sdk-core@2.4.1
SDK for Node.js
umanam
 umanam
23 Jun 2020 (an hour ago)

I'm using ibm-watson@5.6 and it is using  ibm-cloud-sdk-core@2.4.1. This is using ts-jest as dependency and loading older version ts-jest@24.3.0. There is the problem and its failing in contrast build.

I get error "ERR npm WARN ts-jest@24.3.0 requires a peer of jest@>=24 <25 but none is installed. You must install peer dependencies yourself." while deploying application, even fixing with these suggestion its not helping. At the end its conflicting on version of yargs-parser library referenced in ts-jest. Please fix the issue with  ibm-cloud-sdk-core package.json, so that it loads correct version of dependencies.
- [ ] A description of the problem you're trying to solve
We want to enable fetch of latest ts-jest  library with latest ibm-cloud-sdk-core@2.4.1.
Testing --- Repackage library ibm-cloud-sdk-core and invoke in a project then try if its pulling latest ts-jest or not.
- [ ] A suggested solution if possible

**Comment by dpopp07** [comment]
Thanks for the issue. We are removing `ts-jest` as a dependency in the next version, which will be v3.0.0, and this problem will go away.

**Comment by dpopp07** [comment]
We were actually able to fix it without a breaking change, this is now fixed in `v2.4.2`
